dir := `mktemp -d`

default:
	wget -r \
		--no-host-directories --no-parent \
		--directory-prefix {{dir}} \
		--convert-links \
		--page-requisites \
		http://localhost:2015/resume || true

	mv {{dir}}/resume {{dir}}/resume.html
	docker run --rm -v {{dir}}:/converted/ arachnysdocker/athenapdf athenapdf /converted/resume.html
	cp {{dir}}/*.pdf ../assets/resume.pdf
