name: Test Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod download

    - name: Install templ
      run: go install github.com/a-h/templ/cmd/templ@latest

    - name: Generate templates
      run: templ generate

    - name: Build website
      run: go run . generate

    - name: Check build output
      run: |
        if [ ! -d "build" ]; then
          echo "Build directory not created"
          exit 1
        fi
        if [ ! -f "build/about.html" ]; then
          echo "Main page not generated"
          exit 1
        fi
        echo "Build verification passed"